# data source config
spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
server:
  port : 8081
