# data source config
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:camunda
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
# logging config
logging:
  level:
    org.camunda.bpm.example: DEBUG
    org.camunda.bpm: INFO
    org.springframework: DEBUG
